id: A9C7CC2C5
base_file: f8122.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:37:17.007460
  last_modified_at: 2022-06-15 20:37:17.007465
