id: A9C7CC2C5
base_file: fAB09.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:37:17.015947
  last_modified_at: 2022-06-15 20:37:17.015953
