id: A9C7CC2C5
base_file: fD998.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:37:17.022445
  last_modified_at: 2022-06-15 20:37:17.022451
